language: cpp
sudo: false

addons:
  apt:
    packages:
    - gthumb
    - build-essential
    - gthumb-dev
    - gnome-common
    - libglib2.0-dev
    - gnome-doc-utils
    - libgtk-3-dev
    - libgconf2-dev
    - libopenexr-dev
  dist: trusty
  os: linux

script: 
  - sed 's/3.4/3.3/g' configure.ac > configure.ac
  - sed 's/3.4/3.3/g' src/openexr_viewer.extension.in.in > src/openexr_viewer.extension.in.in
  - ./autogen.sh --prefix=/usr
  - ./configure
  - make
