language: cpp
sudo: false

addons:
  apt:
    packages:
    - gthumb
    - build-essential
    - gthumb-dev
    - gnome-common
    - libglib2.0-dev
    - gnome-doc-utils
    - libgtk-3-dev
    - libgconf2-dev
    - libopenexr-dev
    - python3 
    - python3-pip
    - python3-setuptools
    - python3-wheel 
    - ninja-build
  dist: bionic
  os: linux

script: 
  - pip3 install --user meson
  - meson build
  - cd build
  - ninja
