language: cpp
sudo: false

addons:
  apt:
    packages:
    - gthumb
    - build-essential
    - gthumb-dev
    - gnome-common
    - libglib2.0-dev
    - gnome-doc-utils
    - libgtk-3-dev
    - libgconf2-dev
    - libopenexr-dev
  dist: trusty
  os: linux

before_script:
  - sed -ri 's/3.4/3.2/g' configure.ac
  - sed -ri 's/3.4/3.2/g' src/openexr_viewer.extension.in.in 

script: ./autogen.sh --prefix=/usr && ./configure && make
